# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db81f8dfa7c0c125393ba196e2c9ae6252ef6fc866ce7052a5cbb4dbac7954b1041d3d94d3db1896080927b25057880c3a4980fb538f865eb6422c5fd91ae06

test:
  secret_key_base: 68a082d4026734b057050e0a76b55ff0cc71a0162851f4b0870830d853b4f59f059185c4b1123116ec7b7f6dc1b936f5d6b9ce51793c1aa5d82be9b29dda4b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d1d2096dffba52fcdaa132be37b953222ceb40b64739f4dadd7f060df732702baadbcfd125cb1e727f0268aa923e7b270585193c77c63d63fe7d263f3fd252a9
